version: '3.8'

services:
  mcp-server:
    build: .
    container_name: openshift-must-gather-mcp
    environment:
      - MCP_SERVER_NAME=openshift-must-gather
      - MCP_SERVER_VERSION=1.0.0
      - MCP_STORAGE_DIR=/app/storage
      - MCP_LOG_LEVEL=INFO
      - MCP_STRUCTURED_LOGGING=true
      - MCP_MAX_FILE_SIZE_MB=500
      - MCP_ENABLE_CLUSTER_ANALYSIS=true
      - MCP_ENABLE_NODE_ANALYSIS=true
      - MCP_ENABLE_POD_ANALYSIS=true
      - MCP_ENABLE_LOG_ANALYSIS=false
    volumes:
      - ./storage:/app/storage
      - ./must-gather-files:/app/input:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", '{"method": "ping"}', "|", "python", "-m", "mcp-must-gather-parser"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development version with hot reload
  mcp-server-dev:
    build: .
    container_name: openshift-must-gather-mcp-dev
    command: ["python", "-m", "mcp-must-gather-parser.cli", "server", "--log-level", "DEBUG"]
    environment:
      - MCP_SERVER_NAME=openshift-must-gather-dev
      - MCP_SERVER_VERSION=1.0.0-dev
      - MCP_STORAGE_DIR=/app/storage
      - MCP_LOG_LEVEL=DEBUG
      - MCP_STRUCTURED_LOGGING=false
      - MCP_MAX_FILE_SIZE_MB=500
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./must-gather-files:/app/input:ro
    ports:
      - "8001:8000"
    restart: unless-stopped
    profiles:
      - dev

volumes:
  storage:
    driver: local

# Optional: Redis for caching (if needed in future)
redis:
  image: redis:7-alpine
  ports:
    - "6379:6379"
  volumes:
    - redis_data:/data
  restart: unless-stopped
  profiles:
    - cache 