[project]
name = "mcp-must-gather-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fast-agent-mcp>=0.2.47",
    "fastmcp>=2.8.0",
    "mcp-agent>=0.1.8",
]
